name: 'KitchenCraft: cooking business'
description: Run the restaurant and enjoy realistic cooking experience in KitchenCraft!
full_description: 'What will you do? Take orders from clients, go shopping for ingredients and tools, and cook the meals. Do everything yourself or hire staff.
<br>
<br>🍳10+ kitchen tools to cook complex meals.
<br>🍕 40+ recipes of different categories: salads, main courses, fast food, desserts etc.
<br>🍅60+ ingredients to buy in the supermarket.
<br>🏠 Lots of restaurant interior upgrades and decorations.
<br>
<br>Work hard to become the best cook and professional restaurant manager with lots of profit and happy clients!'
android: https://play.google.com/store/apps/details?id=com.loudkeysgames.kitchencraft&utm_source=landing
iOS: https://apps.apple.com/app/kitchencraft-cooking-business/id6541761451
web: false
screenshots:
  - 1-screenshot.png
  - 2-screenshot.png
  - 3-screenshot.png
  - 4-screenshot.png
  - 5-screenshot.png
  - 6-screenshot.png
  - 7-screenshot.png
  - 8-screenshot.png
  - 9-screenshot.png
  - 10-screenshot.png
producthunt: false
#companies:
#  - url: https://telegra.ph/Replace-this-link-07-23
#    image: androidpolice.png
#  - url: https://telegra.ph/Replace-this-link-07-23
#    image: producthunt.png
